version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    image: quarkus/cadastro-operacoes-jvm
    container_name: cadastrodeoperacoes-app
    ports:
      - "8080:8080"
